export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';
export const FETCHING_CHART_DATA = 'FETCHING_CHART_DATA';
export const FETCHED_CHART_DATA = 'FETCHED_CHART_DATA';
export const ERROR_CHART_DATA = 'ERROR_CHART_DATA';
